import glob from 'fast-glob';
import path from 'path';
import { getEnabledPlugins, sanitizePath } from './shared.js';
import { writeFile } from './fileHelpers.js';

function start() {
    const plugins = getEnabledPlugins();
    const vueFiles = {};

    for (const pluginName of plugins) {
        const pluginPath = path.join(process.cwd(), 'src/plugins', pluginName);
        if (pluginPath.includes('.gitkeep')) {
            continue;
        }

        const files = glob.sync(sanitizePath(path.join(pluginPath, 'webview/*.vue')));

        for (const file of files) {
            const componentName = path.basename(file, '.vue');
            vueFiles[componentName] = sanitizePath(`../../src/plugins/${pluginName}/webview/${componentName}.vue`);
        }
    }

    const importsHeader = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY CONTENTS\n\n`;
    let content = '//@ts-nocheck\n' + importsHeader;

    content =
        content +
        Object.keys(vueFiles)
            .map((componentName) => {
                return `import ${componentName} from '${vueFiles[componentName]}';`;
            })
            .join('\n');

    content =
        content +
        '\n\nexport const PLUGIN_IMPORTS = {\n' +
        Object.keys(vueFiles)
            .map((componentName) => {
                return `    ${componentName}: ${componentName},`;
            })
            .join('\n') +
        '\n};\n';

    const importPath = sanitizePath(path.join(process.cwd(), 'webview/pages/plugins.ts'));
    writeFile(importPath, content);

    return Object.keys(vueFiles).length;
}

start();
